onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_niosII/clk
add wave -noupdate /tb_niosII/rst
add wave -noupdate /tb_niosII/PC
add wave -noupdate /tb_niosII/i
add wave -noupdate /tb_niosII/j
add wave -noupdate /tb_niosII/f
add wave -noupdate /tb_niosII/k
add wave -noupdate /tb_niosII/result
add wave -noupdate /tb_niosII/dot_product
add wave -noupdate /tb_niosII/r2
add wave -noupdate /tb_niosII/r3
add wave -noupdate /tb_niosII/r4
add wave -noupdate /tb_niosII/r5
add wave -noupdate /tb_niosII/r6
add wave -noupdate /tb_niosII/r7
add wave -noupdate /tb_niosII/r8
add wave -noupdate /tb_niosII/product
add wave -noupdate /tb_niosII/sum
add wave -noupdate /tb_niosII/dut/clk
add wave -noupdate /tb_niosII/dut/rst
add wave -noupdate /tb_niosII/dut/PC
add wave -noupdate /tb_niosII/dut/fetch_dec_instruction
add wave -noupdate /tb_niosII/dut/offset
add wave -noupdate /tb_niosII/dut/jump_in
add wave -noupdate /tb_niosII/dut/dec_exe_reg_data
add wave -noupdate /tb_niosII/dut/dec_exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/dec_exe_wb_reg_wr_data
add wave -noupdate /tb_niosII/dut/exe_dec_reslt_data
add wave -noupdate /tb_niosII/dut/dec_exe_ctrl_sgs
add wave -noupdate /tb_niosII/dut/dec_exe_reg_wr_add
add wave -noupdate /tb_niosII/dut/dec_exe_mux2_hctrl
add wave -noupdate /tb_niosII/dut/dec_exe_mux1_hctrl
add wave -noupdate /tb_niosII/dut/exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/exe_mem_reslt_data_out
add wave -noupdate /tb_niosII/dut/exe_mem_ctrl_sgs
add wave -noupdate /tb_niosII/dut/exe_mem_reg_wr_add
add wave -noupdate /tb_niosII/dut/exe_hctrl_reg_wr_add_st
add wave -noupdate /tb_niosII/dut/mem_wb_memory_data
add wave -noupdate /tb_niosII/dut/mem_exe_reslt_data
add wave -noupdate /tb_niosII/dut/mem_wb_reg_wr_data
add wave -noupdate /tb_niosII/dut/mem_wb_reg_wr_add
add wave -noupdate /tb_niosII/dut/mem_hctrl_reg_wr_add
add wave -noupdate /tb_niosII/dut/mem_wb_reg_wr_en
add wave -noupdate /tb_niosII/dut/mem_wb_rm_data_sel
add wave -noupdate /tb_niosII/dut/wb_exe_reslt_data
add wave -noupdate /tb_niosII/dut/wb_dec_reg_wr_data
add wave -noupdate /tb_niosII/dut/wb_dec_reg_wr_add
add wave -noupdate /tb_niosII/dut/wb_dec_reg_wr_en
add wave -noupdate /tb_niosII/dut/fetch_unit/PC
add wave -noupdate /tb_niosII/dut/fetch_unit/instruction
add wave -noupdate /tb_niosII/dut/fetch_unit/clk
add wave -noupdate /tb_niosII/dut/fetch_unit/rst
add wave -noupdate /tb_niosII/dut/fetch_unit/jump_in
add wave -noupdate /tb_niosII/dut/fetch_unit/offset
add wave -noupdate /tb_niosII/dut/fetch_unit/pc
add wave -noupdate /tb_niosII/dut/fetch_unit/_PC
add wave -noupdate /tb_niosII/dut/fetch_unit/PC_d
add wave -noupdate /tb_niosII/dut/fetch_unit/instruction_d
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_ctrl_sgs
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_reg_wr_add
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_reg_data
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_wb_reg_wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/dec_fetch_br_PC
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_mux2_hctrl
add wave -noupdate /tb_niosII/dut/dec_unit/dec_exe_mux1_hctrl
add wave -noupdate /tb_niosII/dut/dec_unit/branch_taken
add wave -noupdate /tb_niosII/dut/dec_unit/rst
add wave -noupdate /tb_niosII/dut/dec_unit/clk
add wave -noupdate /tb_niosII/dut/dec_unit/wb_dec_reg_wr_en
add wave -noupdate /tb_niosII/dut/dec_unit/fetch_dec_instruction
add wave -noupdate /tb_niosII/dut/dec_unit/wb_dec_reg_wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/exe_dec_reslt_data
add wave -noupdate /tb_niosII/dut/dec_unit/wb_dec_reg_wr_add
add wave -noupdate /tb_niosII/dut/dec_unit/exe_reg_add
add wave -noupdate /tb_niosII/dut/dec_unit/mem_reg_add
add wave -noupdate /tb_niosII/dut/dec_unit/_dec_exe_ctrl_sgs
add wave -noupdate /tb_niosII/dut/dec_unit/_dec_exe_reg_wr_add
add wave -noupdate /tb_niosII/dut/dec_unit/rA
add wave -noupdate /tb_niosII/dut/dec_unit/rB
add wave -noupdate /tb_niosII/dut/dec_unit/rC
add wave -noupdate /tb_niosII/dut/dec_unit/reg_wr_add
add wave -noupdate /tb_niosII/dut/dec_unit/_dec_exe_reg_data
add wave -noupdate /tb_niosII/dut/dec_unit/_dec_exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/data1
add wave -noupdate /tb_niosII/dut/dec_unit/data2
add wave -noupdate /tb_niosII/dut/dec_unit/mem_wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/PC_br
add wave -noupdate /tb_niosII/dut/dec_unit/opcode
add wave -noupdate /tb_niosII/dut/dec_unit/imm16
add wave -noupdate /tb_niosII/dut/dec_unit/opx
add wave -noupdate /tb_niosII/dut/dec_unit/reg_wr
add wave -noupdate /tb_niosII/dut/dec_unit/mem_wr
add wave -noupdate /tb_niosII/dut/dec_unit/mem_rd
add wave -noupdate /tb_niosII/dut/dec_unit/alu_ctrl
add wave -noupdate /tb_niosII/dut/dec_unit/exe_mux2_hctrl
add wave -noupdate /tb_niosII/dut/dec_unit/exe_mux1_hctrl
add wave -noupdate /tb_niosII/dut/dec_unit/memory_rd_add
add wave -noupdate /tb_niosII/dut/dec_unit/memory_wr_add
add wave -noupdate /tb_niosII/dut/dec_unit/reg_rd_data1
add wave -noupdate /tb_niosII/dut/dec_unit/reg_rd_data2
add wave -noupdate /tb_niosII/dut/dec_unit/Itype
add wave -noupdate /tb_niosII/dut/dec_unit/Jtype
add wave -noupdate /tb_niosII/dut/dec_unit/Rtype
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/rd_data1
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/rd_data2
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/clk
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/rst
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/wr_en
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/wr_address
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/rd_address1
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/rd_address2
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/wr_data
add wave -noupdate /tb_niosII/dut/dec_unit/register_unit/i
add wave -noupdate /tb_niosII/dut/exe_unit/exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/exe_unit/exe_dec_reslt_data
add wave -noupdate /tb_niosII/dut/exe_unit/exe_mem_reslt_data_out
add wave -noupdate /tb_niosII/dut/exe_unit/exe_hctrl_reg_wr_add_st
add wave -noupdate /tb_niosII/dut/exe_unit/exe_mem_reg_wr_add
add wave -noupdate /tb_niosII/dut/exe_unit/exe_mem_ctrl_sgs
add wave -noupdate /tb_niosII/dut/exe_unit/clk
add wave -noupdate /tb_niosII/dut/exe_unit/rst
add wave -noupdate /tb_niosII/dut/exe_unit/dec_exe_ctrl_sgs
add wave -noupdate /tb_niosII/dut/exe_unit/dec_exe_reg_wr_add
add wave -noupdate /tb_niosII/dut/exe_unit/dec_exe_reg_data
add wave -noupdate /tb_niosII/dut/exe_unit/wb_exe_reslt_data
add wave -noupdate /tb_niosII/dut/exe_unit/dec_exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/exe_unit/mem_exe_reslt_data
add wave -noupdate /tb_niosII/dut/exe_unit/wb_dec_exe_reslt_data
add wave -noupdate /tb_niosII/dut/exe_unit/mux2_hctr
add wave -noupdate /tb_niosII/dut/exe_unit/mux1_hctr
add wave -noupdate /tb_niosII/dut/exe_unit/_exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/exe_unit/_exe_mem_reslt_data_out
add wave -noupdate /tb_niosII/dut/exe_unit/_exe_mem_memory_rd_wr_add
add wave -noupdate /tb_niosII/dut/exe_unit/_exe_mem_ctrl_sgs
add wave -noupdate /tb_niosII/dut/exe_unit/alu_ctrl
add wave -noupdate /tb_niosII/dut/exe_unit/data1_reg
add wave -noupdate /tb_niosII/dut/exe_unit/data2_reg
add wave -noupdate /tb_niosII/dut/exe_unit/reslt_data_out
add wave -noupdate /tb_niosII/dut/exe_unit/data2
add wave -noupdate /tb_niosII/dut/exe_unit/data1
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wb_memory_data
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wb_reg_wr_data
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wb_reg_wr_add
add wave -noupdate /tb_niosII/dut/mem_unit/mem_hctrl_reg_wr_add
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wb_reg_wr_en
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wb_rm_data_sel
add wave -noupdate /tb_niosII/dut/mem_unit/mem_exe_reslt_data
add wave -noupdate /tb_niosII/dut/mem_unit/clk
add wave -noupdate /tb_niosII/dut/mem_unit/rst
add wave -noupdate /tb_niosII/dut/mem_unit/exe_mem_ctrl_sgs
add wave -noupdate /tb_niosII/dut/mem_unit/exe_mem_wr_data
add wave -noupdate /tb_niosII/dut/mem_unit/exe_mem_reslt_data_out
add wave -noupdate /tb_niosII/dut/mem_unit/exe_mem_reg_wr_add
add wave -noupdate /tb_niosII/dut/mem_unit/reg_wr
add wave -noupdate /tb_niosII/dut/mem_unit/mem_wr
add wave -noupdate /tb_niosII/dut/mem_unit/mem_rd
add wave -noupdate /tb_niosII/dut/mem_unit/memdata
add wave -noupdate /tb_niosII/dut/wb_unit/wb_dec_reg_wr_data
add wave -noupdate /tb_niosII/dut/wb_unit/wb_exe_reslt_data
add wave -noupdate /tb_niosII/dut/wb_unit/wb_dec_reg_wr_en
add wave -noupdate /tb_niosII/dut/wb_unit/wb_dec_reg_wr_add
add wave -noupdate /tb_niosII/dut/wb_unit/mem_wb_memory_data
add wave -noupdate /tb_niosII/dut/wb_unit/mem_wb_reg_wr_data
add wave -noupdate /tb_niosII/dut/wb_unit/mem_wb_reg_wr_en
add wave -noupdate /tb_niosII/dut/wb_unit/mem_wb_rm_data_sel
add wave -noupdate /tb_niosII/dut/wb_unit/mem_wb_reg_wr_add
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {687 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 278
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {880 ns}
